name: Compile

on:
  push:
    branches: [ "*" ]

jobs:
  Compile:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype-dev -y

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: vcpkg integrate install && vcpkg install freetype

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake . -G="MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Configure CMake (*nix)
        if: runner.os != 'Windows'
        run: cmake .

      - name: Compile
        run: cmake --build .