name: Build

on:
  push:
    branches:
    - unstable

jobs:
  Mac:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    
    - name: Clone fpw/XSDK
      run: git clone https://github.com/fpw/XSDK
      working-directory: ./libs
    
    - name: Clone nothings/stb
      run: git clone https://github.com/nothings/stb
      working-directory: ./libs

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: cmake --build .
    
    - uses: actions/upload-artifact@v3
      with:
        name: Static library for macOS
        path: export/lib/mac/libxpdraw.a

  Linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Clone fpw/XSDK
      run: git clone https://github.com/fpw/XSDK
      working-directory: ./libs
    
    - name: Clone nothings/stb
      run: git clone https://github.com/nothings/stb
      working-directory: ./libs

    - name: Install other dependancies
      run: sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev -y
  
    - name: Configure CMake
      run: cmake .

    - name: Build
      run: cmake --build .
    
    - uses: actions/upload-artifact@v3
      with:
        name: Static library for Linux
        path: export/lib/lin/libxpdraw.a
        
  Windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-freetype

    - name: Put MSYS2_MinGW64 on PATH
      # there is not yet an environment variable for this path from msys2/setup-msys2
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Clone fpw/XSDK
      run: git clone https://github.com/fpw/XSDK
      working-directory: ./libs

    - name: Clone nothings/stb
      run: git clone https://github.com/nothings/stb
      working-directory: ./libs

    - name: Configure CMake
      run: cmake . -G "MinGW Makefiles"

    - name: Build
      run: cmake --build .

    - uses: actions/upload-artifact@v3
      with:
        name: Static library for Windows
        path: export/lib/win/libxpdraw.a
