name: Compile

on:
  push:
    branches: [ "*" ]

jobs:
  Compile:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev -y

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: cmake . -G "MinGW Makefiles"

    - name: Configure CMake (*nix)
      if: runner.os != 'Windows'
      run: cmake . 

    - name: Build
      run: cmake --build .